[package]
name = "wasm_import_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type =["cdylib"]

[dependencies]
# ...

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]